 board: [ "nice_nano_v2" ]
 shield: [ "micropad_hw" ]
 include:
   - board: nice_nano_v2
     shield: micropad_hw
     snippet: studio-rpc-usb-uart
     cmake-args: -DCONFIG_ZMK_STUDIO=y
     artifact-name: micropad
 