name: Build ZMK firmware
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    # Add secrets: inherit
    secrets: inherit
    with:
      # Add explicit quotes to string values
      board: "nice_nano_v2"
      shield: "micropad_hw"
      # Add back artifact-name for completeness
      artifact-name: "firmware"