name: Build ZMK firmware
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        # DEFINE YOUR TARGET BOARD/SHIELD HERE:
        include:
          - board: nice_nano_v2
            shield: micropad_hw # <<< Make sure this is correct

    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    with:
      board: ${{ matrix.board }}
      shield: ${{ matrix.shield }}