name: Build ZMK firmware
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    # Define the build matrix
    strategy:
      fail-fast: false
      matrix:
        include:
          - board: nice_nano_v2
            shield: micropad_hw # Your specific board and shield

    # Call the reusable workflow. It will automatically use the
    # board and shield defined in the matrix above.
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    # REMOVE the entire 'with:' block below this line if it only contained board/shield