name: Build ZMK firmware
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - board: nice_nano_v2
            shield: micropad_hw
            # ADD THIS LINE: Explicitly add an empty cmake-args
            cmake-args: ""

    # Call the reusable workflow (still no 'with:' block needed here)
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main