name: Build ZMK firmware
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - board: nice_nano_v2
            shield: micropad_hw
            # ADD an explicit artifact-name
            artifact-name: firmware # You can name this whatever you like
            cmake-args: ""

    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    # ADD secrets: inherit below uses:
    secrets: inherit
    # Still NO 'with:' block here