name: Build ZMK firmware (Manual West)

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container: # Use a container with build dependencies pre-installed
      image: zmkfirmware/zmk-build-arm:stable
      options: --user root # Run as root to avoid permission issues

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Setup Python virtual environment (optional but good practice in containers)
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8' # ZMK typically uses Python 3.8+

      - name: Create and Activate Virtualenv
        run: |
          python -m venv .venv
          source .venv/bin/activate

      # Install west and dependencies
      - name: Install west and other dependencies
        run: |
          pip install west==1.1.0 # Pin west version for stability
          pip install -r zephyr/scripts/requirements-base.txt
          pip install -r zmk/scripts/requirements.txt

      # Initialize west (using -l config points to your config repo)
      - name: West Init
        run: west init -l config

      # Update west dependencies (fetches ZMK, Zephyr, etc.)
      - name: West Update
        run: west update

      # Export Zephyr CMake package (needed by west build)
      - name: West Export Zephyr CMake package
        run: west zephyr-export

      # <<< --- THE ACTUAL BUILD COMMAND --- >>>
      # Build the firmware for your specific board and shield
      - name: West Build Micropad
        run: |
          west build -d build/micropad \
                     -s zmk/app \
                     -b nice_nano_v2 -- \
                     -DSHIELD=micropad_hw \
                     -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"

      # Archive the build artifact (the UF2 file)
      - name: Archive firmware
        uses: actions/upload-artifact@v3
        with:
          name: micropad_firmware-nice_nano_v2 # Customize artifact name if desired
          path: |
            build/micropad/zephyr/zmk.uf2
            # Optionally include .hex if needed
            # build/micropad/zephyr/zmk.hex